version: "3"
services:

  web:
    build: 
      context: "."
    image: "star-blog"
    ports:
      - "80:8080"
    depends_on:
      - api
    networks: 
      - my_app
    environment:
      API_SERVICE_HOST: api
    

  api:
    build: 
      context: "."
      dockerfile: "api.Dockerfile"
    image: "star-blog-api"
    ports:
      - "8000:8000"
    networks: 
      - my_app
    volumes:
      - ./md:/home/node/app/md

networks:
   my_app:
     driver: bridge